// <auto-generated />
using System;
using GamerParadise.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GamerParadise.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GamerParadise.DataAccess.Models.CreditCard", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("CSC")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<string>("CardNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("ExpirationMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpirationYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("NameOnCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("DeveloperId");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            DeveloperId = 1,
                            IsArchived = false,
                            Name = "Hidden Path Entertainment"
                        },
                        new
                        {
                            DeveloperId = 2,
                            IsArchived = false,
                            Name = "Nintendo EPD"
                        },
                        new
                        {
                            DeveloperId = 3,
                            IsArchived = false,
                            Name = "Unknown Developer"
                        },
                        new
                        {
                            DeveloperId = 4,
                            IsArchived = false,
                            Name = "Psyonix LLC"
                        },
                        new
                        {
                            DeveloperId = 5,
                            IsArchived = false,
                            Name = "Rebuilt Games"
                        },
                        new
                        {
                            DeveloperId = 6,
                            IsArchived = false,
                            Name = "NetherRealm Studios"
                        },
                        new
                        {
                            DeveloperId = 7,
                            IsArchived = false,
                            Name = "DICE"
                        },
                        new
                        {
                            DeveloperId = 8,
                            IsArchived = false,
                            Name = "Ubisoft"
                        },
                        new
                        {
                            DeveloperId = 9,
                            IsArchived = false,
                            Name = "Rockstar Games"
                        },
                        new
                        {
                            DeveloperId = 10,
                            IsArchived = false,
                            Name = "IO Interactive"
                        },
                        new
                        {
                            DeveloperId = 11,
                            IsArchived = false,
                            Name = "Titan Forge Games"
                        },
                        new
                        {
                            DeveloperId = 12,
                            IsArchived = false,
                            Name = "First Watch Games"
                        },
                        new
                        {
                            DeveloperId = 13,
                            IsArchived = false,
                            Name = "Gearbox Software"
                        },
                        new
                        {
                            DeveloperId = 14,
                            IsArchived = false,
                            Name = "Playground Games"
                        },
                        new
                        {
                            DeveloperId = 15,
                            IsArchived = false,
                            Name = "Maxis"
                        },
                        new
                        {
                            DeveloperId = 16,
                            IsArchived = false,
                            Name = "Colossal Order Ltd."
                        },
                        new
                        {
                            DeveloperId = 17,
                            IsArchived = false,
                            Name = "Firaxis Games"
                        },
                        new
                        {
                            DeveloperId = 18,
                            IsArchived = false,
                            Name = "Paradox Development Studio"
                        },
                        new
                        {
                            DeveloperId = 19,
                            IsArchived = false,
                            Name = "Fury Studios"
                        },
                        new
                        {
                            DeveloperId = 20,
                            IsArchived = false,
                            Name = "Bungie"
                        },
                        new
                        {
                            DeveloperId = 21,
                            IsArchived = false,
                            Name = "Relic Entertainment"
                        },
                        new
                        {
                            DeveloperId = 22,
                            IsArchived = false,
                            Name = "Facepunch Studios"
                        },
                        new
                        {
                            DeveloperId = 23,
                            IsArchived = false,
                            Name = "Visual Concepts"
                        },
                        new
                        {
                            DeveloperId = 24,
                            IsArchived = false,
                            Name = "Rare Ltd."
                        });
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("RatingId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Description = "Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem with easy-to-understand controls and fluid, physics-driven competition.",
                            DeveloperId = 4,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = true,
                            Name = "Rocket League",
                            PublisherId = 4,
                            RatingId = 1
                        },
                        new
                        {
                            GameId = 2,
                            Description = "Pummel Party is a 4-8 player online and local-multiplayer party game. Pummel friends or AI using a wide array of absurd items in the board mode and compete to destroy friendships in the unique collection of minigames.",
                            DeveloperId = 5,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = false,
                            IsTrending = false,
                            Name = "Pummel Party",
                            PublisherId = 5,
                            RatingId = 1
                        },
                        new
                        {
                            GameId = 3,
                            Description = "Age of Empires II: Definitive Edition features “The Last Khans” with 3 new campaigns and 4 new Civilizations. Frequent updates include events, additional content, new game modes, and enhanced features with the recent addition of Co-Op mode!",
                            DeveloperId = 1,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = false,
                            IsTrending = false,
                            Name = "Age Of Empires II",
                            PublisherId = 6,
                            RatingId = 4
                        },
                        new
                        {
                            GameId = 4,
                            Description = "Mortal Kombat is back and better than ever in the next evolution of the iconic franchise.",
                            DeveloperId = 6,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = false,
                            IsTrending = false,
                            Name = "Mortal Kombat 11",
                            PublisherId = 7,
                            RatingId = 2
                        },
                        new
                        {
                            GameId = 5,
                            Description = "In this game you are playing the role of the Mario. You are going through the Mushroom Kingdom, surviving the forces of the antagonist Bowser, and saving Princess Toadstool. Mario should reach the flag pole at the end of each level to win the game.",
                            DeveloperId = 2,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = false,
                            Name = "Super Mario Bros",
                            PublisherId = 2,
                            RatingId = 1
                        },
                        new
                        {
                            GameId = 6,
                            Description = "Battlefield™ 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise. Adapt and overcome in a near-future world transformed by disorder.",
                            DeveloperId = 7,
                            IsArchived = false,
                            IsNew = true,
                            IsPopular = true,
                            IsTrending = true,
                            Name = "Battlefield 2042",
                            PublisherId = 8,
                            RatingId = 2
                        },
                        new
                        {
                            GameId = 7,
                            Description = "Dive into the gritty world of a modern-day guerrilla revolution to liberate a nation from its oppressive dictators.",
                            DeveloperId = 8,
                            IsArchived = false,
                            IsNew = true,
                            IsPopular = true,
                            IsTrending = true,
                            Name = "Far Cry 6",
                            PublisherId = 9,
                            RatingId = 2
                        },
                        new
                        {
                            GameId = 8,
                            Description = "When a young street hustler, a retired bank robber and a terrifying psychopath land themselves in trouble, they must pull off a series of dangerous heists to survive in a city in which they can trust nobody, least of all each other.",
                            DeveloperId = 9,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = false,
                            Name = "Grand Theft Auto 5",
                            PublisherId = 10,
                            RatingId = 2
                        },
                        new
                        {
                            GameId = 9,
                            Description = "Death Awaits. Agent 47 returns in HITMAN 3, the dramatic conclusion to the World of Assassination trilogy.",
                            DeveloperId = 10,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = false,
                            Name = "Hitman 3",
                            PublisherId = 11,
                            RatingId = 2
                        },
                        new
                        {
                            GameId = 10,
                            Description = "Join 35+ million players in SMITE, the Battleground of the Gods! Wield Thor’s hammer, turn your foes to stone as Medusa, or flex your divine power as one of 100+ other mythological icons. Become a God.",
                            DeveloperId = 11,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = false,
                            IsTrending = false,
                            Name = "SMITE",
                            PublisherId = 12,
                            RatingId = 4
                        },
                        new
                        {
                            GameId = 11,
                            Description = "You are Ajay Ghale. Traveling to Kyrat, you find yourself caught up in a civil war to overthrow the twisted dictator Pagan Min.",
                            DeveloperId = 8,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = false,
                            Name = "Far Cry 4",
                            PublisherId = 9,
                            RatingId = 2
                        },
                        new
                        {
                            GameId = 12,
                            Description = "Join 20+ million players in Rogue Company, the ultimate third-person tactical action shooter! Become an agent of Rogue Company and wield powerful weapons, high-tech gadgets, and game-changing abilities. Accept the mission and jump into a variety of 4v4 and 6v6 game modes.",
                            DeveloperId = 12,
                            IsArchived = false,
                            IsNew = true,
                            IsPopular = false,
                            IsTrending = true,
                            Name = "Rogue Company",
                            PublisherId = 12,
                            RatingId = 5
                        },
                        new
                        {
                            GameId = 13,
                            Description = "The original shooter-looter returns, packing bazillions of guns and a mayhem-fueled adventure! Blast through new worlds & enemies and save your home from the most ruthless cult leaders in the galaxy.",
                            DeveloperId = 13,
                            IsArchived = false,
                            IsNew = true,
                            IsPopular = false,
                            IsTrending = false,
                            Name = "Borderlands 3",
                            PublisherId = 13,
                            RatingId = 2
                        },
                        new
                        {
                            GameId = 14,
                            Description = "Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action in hundreds of the world’s greatest cars.",
                            DeveloperId = 14,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = false,
                            IsTrending = false,
                            Name = "Forza Horizon 5",
                            PublisherId = 6,
                            RatingId = 1
                        },
                        new
                        {
                            GameId = 15,
                            Description = "Play with life and discover the possibilities. Unleash your imagination and create a world of Sims that’s wholly unique. Explore and customize every detail from Sims to homes–and much more.",
                            DeveloperId = 15,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = false,
                            Name = "The Sims 4",
                            PublisherId = 8,
                            RatingId = 4
                        },
                        new
                        {
                            GameId = 16,
                            Description = "Cities: Skylines is a modern take on the classic city simulation. The game introduces new game play elements to realize the thrill and hardships of creating and maintaining a real city whilst expanding on some well-established tropes of the city building experience.",
                            DeveloperId = 16,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = false,
                            IsTrending = false,
                            Name = "Cities: Skylines",
                            PublisherId = 14,
                            RatingId = 1
                        },
                        new
                        {
                            GameId = 17,
                            Description = "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?",
                            DeveloperId = 3,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = true,
                            Name = "Stardew Valley",
                            PublisherId = 3,
                            RatingId = 3
                        },
                        new
                        {
                            GameId = 18,
                            Description = "Civilization VI offers new ways to interact with your world, expand your empire across the map, advance your culture, and compete against history’s greatest leaders to build a civilization that will stand the test of time. Play as one of 20 historical leaders including Roosevelt (America) and Victoria (England).",
                            DeveloperId = 17,
                            IsArchived = false,
                            IsNew = true,
                            IsPopular = false,
                            IsTrending = true,
                            Name = "Sid Meier's Civilization VI",
                            PublisherId = 13,
                            RatingId = 3
                        },
                        new
                        {
                            GameId = 19,
                            Description = "Paradox Development Studio brings you the sequel to one of the most popular strategy games ever made. Crusader Kings III is the heir to a long legacy of historical grand strategy experiences and arrives with a host of new ways to ensure the success of your royal house.",
                            DeveloperId = 18,
                            IsArchived = false,
                            IsNew = true,
                            IsPopular = false,
                            IsTrending = false,
                            Name = "Crusader Kings III",
                            PublisherId = 14,
                            RatingId = 4
                        },
                        new
                        {
                            GameId = 20,
                            Description = "In Kingdom Two Crowns, players must work in the brand-new solo or co-op campaign mode to build their kingdom and secure it from the threat of the Greed. Experience new technology, units, enemies, mounts, and secrets in the next evolution of the award-winning micro strategy franchise!",
                            DeveloperId = 19,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = false,
                            IsTrending = false,
                            Name = "Kingdom Two Crowns",
                            PublisherId = 15,
                            RatingId = 3
                        },
                        new
                        {
                            GameId = 21,
                            Description = "Dynamic seasons change everything at the world’s greatest automotive festival. Go it alone or team up with others to explore beautiful and historic Britain in a shared open world.",
                            DeveloperId = 14,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = false,
                            Name = "Forza Horizon 4",
                            PublisherId = 6,
                            RatingId = 1
                        },
                        new
                        {
                            GameId = 22,
                            Description = "Destiny 2 is an action MMO with a single evolving world that you and your friends can join anytime, anywhere.",
                            DeveloperId = 20,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = true,
                            Name = "Destiny 2",
                            PublisherId = 16,
                            RatingId = 4
                        },
                        new
                        {
                            GameId = 23,
                            Description = "One of the most beloved real-time strategy games returns to glory with Age of Empires IV, putting you at the center of epic historical battles that shaped the world.",
                            DeveloperId = 21,
                            IsArchived = false,
                            IsNew = true,
                            IsPopular = true,
                            IsTrending = true,
                            Name = "Age of Empires IV",
                            PublisherId = 6,
                            RatingId = 4
                        },
                        new
                        {
                            GameId = 24,
                            Description = "Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, RDR2 is the epic tale of outlaw Arthur Morgan and the infamous Van der Linde gang, on the run across America at the dawn of the modern age. Also includes access to the shared living world of Red Dead Online.",
                            DeveloperId = 9,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = false,
                            Name = "Red Dead Redemption 2",
                            PublisherId = 10,
                            RatingId = 2
                        },
                        new
                        {
                            GameId = 25,
                            Description = "The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife and other inhabitants, the environment, other survivors. Do whatever it takes to last another night.",
                            DeveloperId = 22,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = false,
                            Name = "Rust",
                            PublisherId = 17,
                            RatingId = 2
                        },
                        new
                        {
                            GameId = 26,
                            Description = "NBA 2K22 puts the entire basketball universe in your hands. Anyone, anywhere can hoop in NBA 2K22.",
                            DeveloperId = 23,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = false,
                            IsTrending = false,
                            Name = "NBA 2K22",
                            PublisherId = 13,
                            RatingId = 1
                        },
                        new
                        {
                            GameId = 27,
                            Description = "Sea of Thieves offers the essential pirate experience, from sailing and fighting to exploring and looting – everything you need to live the pirate life and become a legend in your own right. With no set roles, you have complete freedom to approach the world, and other players, however you choose.",
                            DeveloperId = 24,
                            IsArchived = false,
                            IsNew = false,
                            IsPopular = true,
                            IsTrending = false,
                            Name = "Sea of Thieves",
                            PublisherId = 6,
                            RatingId = 4
                        });
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.GameGenre", b =>
                {
                    b.Property<int>("GameGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("GameGenreId");

                    b.HasIndex("GameId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GameGenreId = 1,
                            GameId = 1,
                            GenreId = 14
                        },
                        new
                        {
                            GameGenreId = 2,
                            GameId = 1,
                            GenreId = 15
                        },
                        new
                        {
                            GameGenreId = 3,
                            GameId = 2,
                            GenreId = 11
                        },
                        new
                        {
                            GameGenreId = 4,
                            GameId = 2,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 5,
                            GameId = 3,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 6,
                            GameId = 3,
                            GenreId = 9
                        },
                        new
                        {
                            GameGenreId = 7,
                            GameId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            GameGenreId = 8,
                            GameId = 4,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 9,
                            GameId = 5,
                            GenreId = 2
                        },
                        new
                        {
                            GameGenreId = 10,
                            GameId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            GameGenreId = 11,
                            GameId = 6,
                            GenreId = 7
                        },
                        new
                        {
                            GameGenreId = 12,
                            GameId = 6,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 13,
                            GameId = 7,
                            GenreId = 1
                        },
                        new
                        {
                            GameGenreId = 14,
                            GameId = 7,
                            GenreId = 7
                        },
                        new
                        {
                            GameGenreId = 15,
                            GameId = 7,
                            GenreId = 12
                        },
                        new
                        {
                            GameGenreId = 16,
                            GameId = 7,
                            GenreId = 10
                        },
                        new
                        {
                            GameGenreId = 17,
                            GameId = 8,
                            GenreId = 12
                        },
                        new
                        {
                            GameGenreId = 18,
                            GameId = 8,
                            GenreId = 1
                        },
                        new
                        {
                            GameGenreId = 19,
                            GameId = 8,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 20,
                            GameId = 9,
                            GenreId = 1
                        },
                        new
                        {
                            GameGenreId = 21,
                            GameId = 10,
                            GenreId = 1
                        },
                        new
                        {
                            GameGenreId = 22,
                            GameId = 10,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 23,
                            GameId = 11,
                            GenreId = 12
                        },
                        new
                        {
                            GameGenreId = 24,
                            GameId = 11,
                            GenreId = 1
                        },
                        new
                        {
                            GameGenreId = 25,
                            GameId = 11,
                            GenreId = 11
                        },
                        new
                        {
                            GameGenreId = 26,
                            GameId = 11,
                            GenreId = 10
                        },
                        new
                        {
                            GameGenreId = 27,
                            GameId = 12,
                            GenreId = 1
                        },
                        new
                        {
                            GameGenreId = 28,
                            GameId = 12,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 29,
                            GameId = 12,
                            GenreId = 7
                        },
                        new
                        {
                            GameGenreId = 30,
                            GameId = 13,
                            GenreId = 16
                        },
                        new
                        {
                            GameGenreId = 31,
                            GameId = 13,
                            GenreId = 1
                        },
                        new
                        {
                            GameGenreId = 32,
                            GameId = 13,
                            GenreId = 7
                        },
                        new
                        {
                            GameGenreId = 33,
                            GameId = 13,
                            GenreId = 11
                        },
                        new
                        {
                            GameGenreId = 34,
                            GameId = 14,
                            GenreId = 10
                        },
                        new
                        {
                            GameGenreId = 35,
                            GameId = 14,
                            GenreId = 14
                        },
                        new
                        {
                            GameGenreId = 36,
                            GameId = 14,
                            GenreId = 12
                        },
                        new
                        {
                            GameGenreId = 37,
                            GameId = 15,
                            GenreId = 8
                        },
                        new
                        {
                            GameGenreId = 38,
                            GameId = 16,
                            GenreId = 13
                        },
                        new
                        {
                            GameGenreId = 39,
                            GameId = 16,
                            GenreId = 8
                        },
                        new
                        {
                            GameGenreId = 40,
                            GameId = 17,
                            GenreId = 16
                        },
                        new
                        {
                            GameGenreId = 41,
                            GameId = 18,
                            GenreId = 9
                        },
                        new
                        {
                            GameGenreId = 42,
                            GameId = 19,
                            GenreId = 9
                        },
                        new
                        {
                            GameGenreId = 43,
                            GameId = 19,
                            GenreId = 16
                        },
                        new
                        {
                            GameGenreId = 44,
                            GameId = 19,
                            GenreId = 8
                        },
                        new
                        {
                            GameGenreId = 45,
                            GameId = 20,
                            GenreId = 9
                        },
                        new
                        {
                            GameGenreId = 46,
                            GameId = 20,
                            GenreId = 10
                        },
                        new
                        {
                            GameGenreId = 47,
                            GameId = 21,
                            GenreId = 14
                        },
                        new
                        {
                            GameGenreId = 48,
                            GameId = 21,
                            GenreId = 12
                        },
                        new
                        {
                            GameGenreId = 49,
                            GameId = 21,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 50,
                            GameId = 22,
                            GenreId = 12
                        },
                        new
                        {
                            GameGenreId = 51,
                            GameId = 22,
                            GenreId = 7
                        },
                        new
                        {
                            GameGenreId = 52,
                            GameId = 23,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 53,
                            GameId = 23,
                            GenreId = 9
                        },
                        new
                        {
                            GameGenreId = 54,
                            GameId = 24,
                            GenreId = 12
                        },
                        new
                        {
                            GameGenreId = 55,
                            GameId = 24,
                            GenreId = 10
                        },
                        new
                        {
                            GameGenreId = 56,
                            GameId = 25,
                            GenreId = 4
                        },
                        new
                        {
                            GameGenreId = 57,
                            GameId = 25,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 58,
                            GameId = 26,
                            GenreId = 15
                        },
                        new
                        {
                            GameGenreId = 59,
                            GameId = 26,
                            GenreId = 8
                        },
                        new
                        {
                            GameGenreId = 60,
                            GameId = 27,
                            GenreId = 6
                        },
                        new
                        {
                            GameGenreId = 61,
                            GameId = 27,
                            GenreId = 10
                        },
                        new
                        {
                            GameGenreId = 62,
                            GameId = 27,
                            GenreId = 12
                        });
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.GameLibrary", b =>
                {
                    b.Property<int>("GameLibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GameLibraryId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("GameLibraries");
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Description = "Intense high performance game that requires attention and focus.",
                            IsArchived = false,
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            Description = "A skill based left to right 2D jump game.",
                            IsArchived = false,
                            Name = "Platformer"
                        },
                        new
                        {
                            GenreId = 3,
                            Description = "A game intended to cause mild psychological discomfort and fear.",
                            IsArchived = false,
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = 4,
                            Description = "Intended to challenge the player and force them to get creative to survive.",
                            IsArchived = false,
                            Name = "Survival"
                        },
                        new
                        {
                            GenreId = 5,
                            Description = "A fun local or online multiplayer with general fun and laughter.",
                            IsArchived = false,
                            Name = "Party"
                        },
                        new
                        {
                            GenreId = 6,
                            Description = "Online competetive gaming experience in a wide range of environments.",
                            IsArchived = false,
                            Name = "Multiplayer"
                        },
                        new
                        {
                            GenreId = 7,
                            Description = "Emphasizes the use of weaponry and explosives in combat with NPCs or online players.",
                            IsArchived = false,
                            Name = "Shooter"
                        },
                        new
                        {
                            GenreId = 8,
                            Description = "Replicates the real life activity displayed in the game with much detail.",
                            IsArchived = false,
                            Name = "Simulation"
                        },
                        new
                        {
                            GenreId = 9,
                            Description = "A game that forces you to get creative with solutions to outplay the enemy.",
                            IsArchived = false,
                            Name = "Strategy"
                        },
                        new
                        {
                            GenreId = 10,
                            Description = "A generally story driven game that is often single player and involves choices.",
                            IsArchived = false,
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreId = 11,
                            Description = "A multiplayer game that promotes and encourages friends to work together to accomplish goals.",
                            IsArchived = false,
                            Name = "Co-op"
                        },
                        new
                        {
                            GenreId = 12,
                            Description = "A game that promotes freedom to roam in a large and expansive map with many opportunities and surpises.",
                            IsArchived = false,
                            Name = "Open World"
                        },
                        new
                        {
                            GenreId = 13,
                            Description = "A game with the aspect of building from a set starting point for the purpose of progress.",
                            IsArchived = false,
                            Name = "Building"
                        },
                        new
                        {
                            GenreId = 14,
                            Description = "A game featuring vehicles that compete to be the first to navigate some kind of track or obstacle.",
                            IsArchived = false,
                            Name = "Racing"
                        },
                        new
                        {
                            GenreId = 15,
                            Description = "A game involving one or many different kinds of sports around the world.",
                            IsArchived = false,
                            Name = "Sports"
                        },
                        new
                        {
                            GenreId = 16,
                            Description = "A game in which you take over the life of a character and influence their and their world's outcome based on your decisions.",
                            IsArchived = false,
                            Name = "RPG"
                        });
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanBetaTest")
                        .HasColumnType("bit");

                    b.Property<bool>("CanPlayOnTwoDevices")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("HasAccessToAllGames")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPersonalLibrary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<byte>("MaxDownloads")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RecievesNewsletter")
                        .HasColumnType("bit");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            CanBetaTest = false,
                            CanPlayOnTwoDevices = false,
                            Description = "Our Classic plan will grant you access to thousands of games instantly and we will provide you a game library for up to 5 downloaded games at a time!",
                            HasAccessToAllGames = false,
                            HasPersonalLibrary = true,
                            IsArchived = false,
                            MaxDownloads = (byte)5,
                            Name = "Classic",
                            Price = 12.99m,
                            RecievesNewsletter = true
                        },
                        new
                        {
                            PlanId = 2,
                            CanBetaTest = true,
                            CanPlayOnTwoDevices = false,
                            Description = "Our Standard plan will grant you access to thousands of games instantly and we will provide you a game library for up to 10 downloaded games at a time! You will also get exclusive beta testing access to newly developing games!",
                            HasAccessToAllGames = true,
                            HasPersonalLibrary = true,
                            IsArchived = false,
                            MaxDownloads = (byte)10,
                            Name = "Standard",
                            Price = 16.99m,
                            RecievesNewsletter = true
                        },
                        new
                        {
                            PlanId = 3,
                            CanBetaTest = true,
                            CanPlayOnTwoDevices = true,
                            Description = "Our Ultimate plan will grant you access to thousands of games instantly and we will provide you a game library for up to 15 downloaded games at a time across multiple devices! You will also get exclusive beta testing access to newly developing games!",
                            HasAccessToAllGames = true,
                            HasPersonalLibrary = true,
                            IsArchived = false,
                            MaxDownloads = (byte)15,
                            Name = "Ultimate",
                            Price = 25.99m,
                            RecievesNewsletter = true
                        });
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("PublisherId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PublisherId = 1,
                            IsArchived = false,
                            Name = "Microsoft"
                        },
                        new
                        {
                            PublisherId = 2,
                            IsArchived = false,
                            Name = "Nintendo"
                        },
                        new
                        {
                            PublisherId = 3,
                            IsArchived = false,
                            Name = "Unknown Publisher"
                        },
                        new
                        {
                            PublisherId = 4,
                            IsArchived = false,
                            Name = "Psyonix LLC"
                        },
                        new
                        {
                            PublisherId = 5,
                            IsArchived = false,
                            Name = "Rebuilt Games"
                        },
                        new
                        {
                            PublisherId = 6,
                            IsArchived = false,
                            Name = "Xbox Game Studios"
                        },
                        new
                        {
                            PublisherId = 7,
                            IsArchived = false,
                            Name = "Warner Bros Games"
                        },
                        new
                        {
                            PublisherId = 8,
                            IsArchived = false,
                            Name = "Electronic Arts"
                        },
                        new
                        {
                            PublisherId = 9,
                            IsArchived = false,
                            Name = "Ubisoft"
                        },
                        new
                        {
                            PublisherId = 10,
                            IsArchived = false,
                            Name = "Rockstar Games"
                        },
                        new
                        {
                            PublisherId = 11,
                            IsArchived = false,
                            Name = "IO Interactive"
                        },
                        new
                        {
                            PublisherId = 12,
                            IsArchived = false,
                            Name = "Hi-Rez Studios"
                        },
                        new
                        {
                            PublisherId = 13,
                            IsArchived = false,
                            Name = "2K"
                        },
                        new
                        {
                            PublisherId = 14,
                            IsArchived = false,
                            Name = "Paradox Interactive"
                        },
                        new
                        {
                            PublisherId = 15,
                            IsArchived = false,
                            Name = "Raw Fury"
                        },
                        new
                        {
                            PublisherId = 16,
                            IsArchived = false,
                            Name = "Bungie"
                        },
                        new
                        {
                            PublisherId = 17,
                            IsArchived = false,
                            Name = "Facepunch Studios"
                        });
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("RatingId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            Description = "Content is generally suitable for all ages. May contain minimal cartoon, fantasy or mild violence and/or infrequent use of mild language.",
                            IsArchived = false,
                            Name = "Everyone"
                        },
                        new
                        {
                            RatingId = 2,
                            Description = "Content is generally suitable for ages 17 and up. May contain intense violence, blood and gore, sexual content and/or strong language.",
                            IsArchived = false,
                            Name = "Mature 17+"
                        },
                        new
                        {
                            RatingId = 3,
                            Description = "Content is generally suitable for ages 10 and up. May contain more cartoon, fantasy or mild violence, mild language and/or minimal suggestive themes.",
                            IsArchived = false,
                            Name = "Everyone 10+"
                        },
                        new
                        {
                            RatingId = 4,
                            Description = "Content is generally suitable for ages 13 and up. May contain violence, suggestive themes, crude humor, minimal blood, simulated gambling and/or infrequent use of strong language.",
                            IsArchived = false,
                            Name = "Teen 13+"
                        },
                        new
                        {
                            RatingId = 5,
                            Description = "Not yet assigned a final ESRB rating. Appears only in advertising, marketing and promotional materials related to a physical (e.g., boxed) video game that is expected to carry an ESRB rating, and should be replaced by a game's rating once it has been assigned.",
                            IsArchived = false,
                            Name = "Rating Pending"
                        },
                        new
                        {
                            RatingId = 6,
                            Description = "Content suitable only for adults ages 18 and up. May include prolonged scenes of intense violence, graphic sexual content and/or gambling with real currency.",
                            IsArchived = false,
                            Name = "Adult 18+"
                        });
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("DateTimeWritten")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<byte>("StarCount")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("Downloads")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("CardId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Responded")
                        .HasColumnType("bit");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "admin@gamerparadise.com",
                            FirstName = "Sam",
                            IsAdmin = true,
                            IsArchived = false,
                            LastName = "Krahn",
                            PasswordHash = "AQAAAAEAACcQAAAAEN4G4vIBq6fnCHTRVN3j9/uNgolKJvD2+BDIm229Yzm//CQZc0lB7ZzZWAiySFjnlg==",
                            Username = "UndeadWolf222"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "bobloblaw123@gmail.com",
                            FirstName = "Bob",
                            IsAdmin = true,
                            IsArchived = false,
                            LastName = "Loblaw",
                            PasswordHash = "AQAAAAEAACcQAAAAEO8KheuRDzmRvQQln7Wfv1Pc0//4p0m/7dBapgh/vL0eVoIpzzwI5fr9uRrKov1Ddw==",
                            Username = "BlahBlahBlah"
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "icvabora@students.ntc.edu",
                            FirstName = "Isaiah",
                            IsAdmin = true,
                            IsArchived = false,
                            LastName = "Vobora",
                            PasswordHash = "AQAAAAEAACcQAAAAEEYvC2iJLEtrOLCMOJ5VbySKqm/0sgJRRnJCuXVsQ32o//EC4wAzmuVOx8ZYdDF5vA==",
                            Username = "godofgames44"
                        });
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.CreditCard", b =>
                {
                    b.HasOne("GamerParadise.DataAccess.Models.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Game", b =>
                {
                    b.HasOne("GamerParadise.DataAccess.Models.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamerParadise.DataAccess.Models.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamerParadise.DataAccess.Models.Rating", "Rating")
                        .WithMany("Games")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.GameGenre", b =>
                {
                    b.HasOne("GamerParadise.DataAccess.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamerParadise.DataAccess.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.GameLibrary", b =>
                {
                    b.HasOne("GamerParadise.DataAccess.Models.Game", "Game")
                        .WithMany("GameLibraries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamerParadise.DataAccess.Models.User", "User")
                        .WithMany("GameLibraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Review", b =>
                {
                    b.HasOne("GamerParadise.DataAccess.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamerParadise.DataAccess.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamerParadise.DataAccess.Models.Subscription", b =>
                {
                    b.HasOne("GamerParadise.DataAccess.Models.CreditCard", "Card")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamerParadise.DataAccess.Models.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamerParadise.DataAccess.Models.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("GamerParadise.DataAccess.Models.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
